### ISSUE TITLE
How to tell if a given tag name is a block tag?

### ISSUE THREAD

**Issue by scottge** [harttle/liquidjs#104]
Given a tag name, how can I pro-grammatically tell if the tag is a block tag? 

"Blocks" are tags that contain a block of template code which is delimited by a {% end<TAGNAME> %} tag.

In Ruby Liquid, I can do it with the following code:

 ```ruby
Liquid::Template.tags[tag_name].ancestors.include?(Liquid::Block)
```

**Comment by harttle** [comment]
No, currently you cannot. End tags are parsed by individual Tag implementation, as a result of which, Liquid don't know whether it expected an end tag.

**Comment by scottge** [comment]
Thanks for the quick answer.

Can I iterate through all registered tags?
Would you consider adding a 'isBlockTag' property to the Tag interface, so that each tag implementation can explicitly tell if it's a block tag or not?

**Comment by harttle** [comment]
I'm considering introduce a `BlockTag` type, for which liquid automatically parse until the corresponding end tag. Then you can test the type either by `instanceof` or `.type` property.

**Comment by scottge** [comment]
Perfect!

**Comment by harttle** [comment]
I find that it'll be a breaking change if we introduce new ways to register tags. Another way is to add an optional, thus not breaking, `type` property indicating the tag type to existing tags. But there're problems still:

1. The tags registered by 3rd party plugins or legacy repos will not have this property, which introduces inconsistency.
2. The redundant property does nothing other than indicating its type. That's why they don't have a type now. And that's because we want to make tags(or user registered tags) ultra powerful.

But still, I can provide a way to access all registered tags and filters. In the meantime, I'm wondering why you want the type, can you provide a use case? Maybe I can help with that.

**Comment by scottge** [comment]
Here is my use case: I need to extract excerpt from content by splitting the content by an expert separator. Here is an example content: 

```
Hello World {% raw %}

aaa
{% endraw %}

The actual content....
```

The excerpt separator could be a new line.  In this case, the above content will give me the excerpt:

```
Hello World {% raw %}
```
As you can see, the raw tag is broken.  So I need to remedy it by checking if the raw tag is a block tag or not.  If it's a block tag.

**Comment by harttle** [comment]
Since block tags always get closed, each time your parser encounters a tag (say, `foo`), just check whether or not there's a corresponding end tag (whose name will be `endfoo`).

This way your parser will not rely on tag implementations. It takes O(n) time to extract excerpt from content of length n. But good news is that the content between `foo` and `endfoo` is also parsed and ready for your remedy use.

**Comment by scottge** [comment]
Thank you for your workaround!  There may be an edge case that does not work with the workaround:

Let's say {% foo %} is not a block tag, and we have another non-block tag called {% endfoo %} - totally an edge case :-)

If I rely on parsing the remaining content to tell if foo is a block tag or not, it could mislead me to believe that foo IS a block tag here.

**Comment by harttle** [comment]
Since there's no plan to support this, closing.
