### ISSUE TITLE
Named arguments are passed to filter as undefined

### ISSUE THREAD

**Issue by stewartknapman** [harttle/liquidjs#113]
Passing named arguments to a filter no longer works, arguments are given but they are all undefined.
It was previously working in version 4.0.0 and I have since upgraded to 7.4.0.

Example:
```
engine.registerFilter('t', function () {
  console.log(arguments);
})
```

```
{{ 'filter.arg.test.1' | t }}
// => Arguments ["filter.arg.test.1", callee: ƒ, Symbol(Symbol.iterator): ƒ]

{{ 'filter.arg.test.2' | t: 'foo', 'bar', 'baz' }}
// => Arguments(4) ["filter.arg.test.2", "foo", "bar", "baz", callee: ƒ, Symbol(Symbol.iterator): ƒ]

{{ 'filter.arg.test.3' | t: arg1: 'foo', arg2: 'bar', arg3: 'baz' }}
// => Arguments(4) ["filter.arg.test.3", undefined, undefined, undefined, callee: ƒ, Symbol(Symbol.iterator): ƒ]
```

In the v4.0.0  `{{ 'filter.arg.test.3' | t: arg1: 'foo', arg2: 'bar', arg3: 'baz' }}` would return the key and value for each argument as seperate arguments. This was fine, I just looped through them and paired them back up. But I wonder if it would be more helpful to return each of them as an object?

**Comment by harttle** [comment]
That's a mistake during the TypesScript refactor. Now I make them work again, but slightly different:

1. Arguments with names now appears as a subarray rather than flattened.
2. Argument key is no longer wrapped with single quotes.

See [this integration test](https://github.com/harttle/liquidjs/blob/ad0930f1523be4ca05c6cc8a061264da6783196b/test/integration/liquid/register-filters.ts#L10) for details.

Any problems please let me know :)

**Comment by stewartknapman** [comment]
@harttle That is magic! It all looks to be working as expected now.
