### ISSUE TITLE
Running tests and developing: Trouble getting started

### ISSUE THREAD

**Issue by stephengardner** [harttle/liquidjs#119]
I've cloned the repo in an attempt to add tags and test them.  Ultimately hoping to understand the structure enough to do a PR for a new feature.

I've noticed a few things, so hoping to address them and be able to ultimately contribute to this project.

1. It looks like you need to have `ts-node` installed globally to be able to run the mocha tests.  I suppose that's worth noting. `npm i -g ts-node`.
2. If you have vscode's [Typescript Auto Compiler](https://marketplace.visualstudio.com/itemdetails?itemName=morissonmaciel.typescript-auto-compiler) enabled, then saving any file in `/test` will perform large-scale compilation for each file, adding the .js/.map, and you'll end up with running your CPU to 100% for a really, really long time and probably need to reboot (laptop specs: i7 16gb 2.80GHz).  Not sure if you are using vscode and/or experienced this with your typescript implementation.  This may just be a note to anyone in the future.
3. On a fresh clone, runing `mocha test/integration/builtin/tags/include.ts`, for example, will take a long time to begin (20s-30s or more, perhaps).  This happens due to the line `new Liquid({})`in the `before` block.  This is likely an issue with `ts-node`, but I'm not sure.  How do you reconcile this?  Is this not happening for you?  To reproduce this, just run `mocha test/integration/builtin/tags/include.ts`.  You can also run a minimal reproduction just using this:
```
// this takes a long time for the test to start up
// location: ./test/integration/custom/tags/some-tag.ts
import Liquid from '../../../../src/liquid';
describe('custom', function() {
  let liquid: Liquid;
  before(function() {
    liquid = new Liquid({});
  });
  it('should output something', function() {});
});
```
You do awesome work on this library, so hope I can understand this more and help out.  Thanks

**Comment by stephengardner** [comment]
Update to 3:
For faster testing, I modified `tsconfig` and added `tsc` for incremental compilation, I am incrementally compiling the typescript and running mocha on the compiled `.js` files out of `/dist`. This is much faster, but doesn't conform to the project as a whole.

**Comment by harttle** [comment]
1. `ts-node` is not required to be installed globally. It's installed as [dev dependency](https://github.com/harttle/liquidjs/blob/7483613b2339e5a6ff320c2802a01f84f18423de/package.json#L86) and required by [mocha.opts](https://github.com/harttle/liquidjs/blob/7483613b2339e5a6ff320c2802a01f84f18423de/test/mocha.opts#L1). Here's a [CI job](https://travis-ci.org/harttle/liquidjs/jobs/514490744) running tests and dist, there's nothing installed globally.
2. I can reproduce this, it's so frustrating and I rebooted many times before figured out what's happening. It seems to be caused by [the watcher](https://github.com/morissonmaciel/vscode-tsc-compiler/blob/67bbb32647fc2c7789e2d239e6bc57894028912d/src/TypeScriptCompiler.ts#L78) watching the generated `.d.ts` files (I added `outDir:"dist"` locally). I've submitted an [issue](https://github.com/morissonmaciel/vscode-tsc-compiler/issues/18) to keep this running. BTW, it's not desirable to use typescript auto compile plugin (and I think it's true for many other repos) since the build tool for liquidjs is not simply `tsc`, it's `rollup`.
3. It's true `ts-node` is unbelievably slow on Windows, but not for MacOS and Linux (the travis CI jobs are fast). I'll look at this and see what's wrong. AFAIK, we should run the unit tests against the source files, not the built or bundled.

**Comment by stephengardner** [comment]
1. When cloning and running on a machine locally, I believe the "mocha" command and the "ts-node" dependency would have to be installed globally, unless I'm mistaken, because they are still global commands when running them.  The CI build will have those installed through whatever CI spin-up happens, I suppose.  So this is mainly just to help people who might be cloning and running a test locally.  I can only speak for Windows machines. 
2. Thanks! I did the same thing, haha.  So the fix would be adding the outDir, is there any reason why this isn't merged?  
3. The travis jobs are lightning fast compared to what I am experiencing.  That's amazing.  Not sure how easy it would be for you to look into that.  But thanks for shedding some light.

Much appreciated.
