### ISSUE TITLE
T filter

### ISSUE THREAD

**Issue by jigs1212** [harttle/liquidjs#149]
Where can i find the 't' filter.

And how do I find the scope/ context in registerFilter.

is there any way to call default filters from custom filter.

**Comment by harttle** [comment]
Can you provide a reference link, since I didn't see a T filter in the [standardfilters](https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb).

According to the [policy described in README.md](https://github.com/harttle/liquidjs#differences-and-limitations), non-standard filters should be placed into plugins. Feel free to share your plugin and make a PR to update the filter list in README.md

**Comment by harttle** [comment]
Anyway this filter will not be implemented in this repo. But as disccussed in #159, there could be a  liquidjs-shopify-plugins for emulating Shopify-proper scenarios. And there will be better reference/guidance for making/using plugins.
