### ISSUE TITLE
Accessing application context inside tag ?

### ISSUE THREAD

**Issue by nequid** [harttle/liquidjs#153]
Is there any way to access express application context(app) inside tag or how can i pass app instance to tag ?

**Comment by harttle** [comment]
Access the context: The `scope` parameter for the `render()` method contains the context, see [register tags](https://github.com/harttle/liquidjs/wiki/Register-Filters-Tags#register-tags). It's the context supposed to be used to render this tag instance, not the original expressjs context (eg. assigments are also included).

Access the instance: There's no such way to access express app by liquid instance or tags since liquid itself is independent from liquidjs. But you can make expressjs app a property of liquid by `liquid.app = <your expressjs app>`. Then write a plugin for all your tags like [this simple plugin example](https://github.com/harttle/liquidjs/wiki/Write-a-Plugin#a-simple-plugin). The `liquid` instance is available inside plugin functions.
