### ISSUE TITLE
Date filter converts time to local timezone

### ISSUE THREAD

**Issue by petuomin** [harttle/liquidjs#236]
Hi there,

There is an issue with the `date` filter that uses javascript's native dates. The timezone of the javascript date is always set to the user's timezone (this is different behaviour than in ruby). For example:
```
new Date("1990-12-31T23:00:00Z")
// -> Tue Jan 01 1991 01:00:00 GMT+0200 (Eastern European Standard Time)
```
The input is parsed correctly, but it's converted to local timezone. (Note that this loses the information of the timezone of the input value). Now if I want to format the date it will show wrong year etc. depending on my timezone. For example, if your computer is set to some other timezone than utc, then the following test will fail:
```
// test/integration/builtin/filters/date.ts

it('should not convert timezones', async function () {
  return test('{{ "1990-12-31T23:00:00Z" | date: "%Y-%m-%dT%H:%M:%S"}}', '1990-12-31T23:00:00')
})
```

**Comment by harttle** [comment]
There's no timezone info in JavaScript Date object thus we can't implement the same behavior as the Ruby version. I'm considering an additional `timezone` parameter (defaults to current timezone offset to be backward compatible) for the `date` filter, like:

```javascript
{{ "1990-12-31T23:00:00Z" | date: "%Y-%m-%dT%H:%M:%S", "+08:00"}}
```

It provides the capability to display date in a specific timezone though it still not compatible with the Ruby version. Another approach is we invent a DateTime type to emulate the Time class in Ruby, which consists a Date object and a timezone offset. What do you think?

**Comment by petuomin** [comment]
Sounds like a new DateTime type is a better solution. If the timezone information is already in the input value then it's a bit annoying that the user is forced to restate it when reformatting the date. (I can envision someone using liquidjs to parse the input value to generate the timezone value :smile:)

It should be some sort of wrapper on the native date though. It's a road to madness trying to figure what timezone was/is being used at which places at what times, and these change over time.

There exist libraries for handling the date stuff, but I see that liquidjs doesn't have dependencies so that might not be a solution you are satisfied with?

**Comment by petuomin** [comment]
I was wondering if you have given any though on this? What kind of solution do you think would be the best?

**Comment by harttle** [comment]
> but I see that liquidjs doesn't have dependencies so that might not be a solution you are satisfied with?

Yeah, liquids implements a strftime on its own. And I agree with you to provide a new wrapper datetime type. But we need try to be backward compatible (e.g. default to current timezone as in JavaScript's Date).

**Comment by petuomin** [comment]
Maybe an option for the Liquid constructor. Something like `preserveTimezones` with default to `false`.

**Comment by petuomin** [comment]
I'd like to get some feedback on the suggested solution before committing to work on it.

**Comment by harttle** [comment]
The key point is there's no timezone infomation inside Date objects (as in Ruby) in JavaScript Date.

And we should be backward compatible, which means the `date` filter still works for original Date objects. One way to implement is trying to extend or encapsulate the JavaScript `Date` and add additional properties to indicate the timezone.

In the meantime, if you find an additional `timezone` argument useful for the `date` filter, that's also OK.

The tricky part is, the default behaviour (without timezone info) cannot be the same with the Ruby version because JavaScript Date will always align to the timezone of the current runtime (different browsers/Node.js env always yield different results given the same source code). In this respect the `preserveTimezones` is useless since the absense of timezone property always mean `preserveTimezones = false`.

The date formatter is located at https://github.com/harttle/liquidjs/blob/master/src/util/strftime.ts . Please let me know if you get stuck.

Hope it helps!

**Comment by wyozi** [comment]
Another problem is that even if you have an extended date object with the timezone included, you'll somehow need to output the date filter format strings in the correct timezone. Maybe some `toLocaleString` hacks would work for that, but it would still be quite hacky.

What about optionally dropping the timezone from date strings passed to `new Date`? Doing `new Date("1990-12-31T23:00:00")` instead of `new Date("1990-12-31T23:00:00Z")` yields a somewhat correct looking date object.

**Comment by petuomin** [comment]
The date should be printed similarly than it is read. So the conversion to the target timezone (defined in the input string) would need to be done. That is not too big a thing though, as there is already a custom strftime for formatting the date.

Dropping the timezone information would prevent implementing features that need the timezone, like conversions to different zones, or location based times. There was the idea of filters that allows the user to specify the timezone. I think it's good to keep in mind when making decisions in this.

**Comment by wyozi** [comment]
@petuomin imo the "conversion to the target timezone" is the difficult part. There is no easy way to convert to given timezone since it's not as simple as addition (unless only numeric integer timezones are supported, and even then DST might pose some problems). For instance, how would you modify the custom strftime to convert the given date to `Asia/Shanghai` timezone?

Taking advantage of [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) would be an option, but as far as I can tell it would require a complete overhaul of strftime and add additional browser requirements. Maybe that's the only way to have a "proper" timezone support though. The author of Luxon goes a bit deeper into this [here](https://moment.github.io/luxon/docs/manual/zones#iana-support).

As far as I can tell, one major issue here is the automatic conversion to local timezone. If the `date` filter just kept the dates and times the same (give timestamp with hour=20, get formatted string with hour=20), the issue would be partially solved. That's why I suggested dropping timezone as one potential solution.

**Comment by tchak** [comment]
Would it be possible to support upcoming Temporal objects as inputs and so enable use of ZonedDateTime?
