### ISSUE TITLE
With strict_variables, can't check if variable is defined

### ISSUE THREAD

**Issue by sschuldenzucker** [harttle/liquidjs#265]
The title says it all: The following code fails if `strict_variables` is set and `somevar` is not defined:
```
{% if somevar %} This is {{ somevar }}. {% else %} Default text. {% endif %}
```

This makes `strict_variables` basically useless as far as I'm concerned. — Which is a shame because it's a really useful feature.

This issue was inherited from the ruby version: https://github.com/Shopify/liquid/issues/1034

### Possible solutions

1. In this particular context (`if` statement with a condition that is a single variable), an undefined variable should simply evaluate to `false`. OR
2. Introduce a special `defined(...)` function or a `defined` keyword.
3. Introduce a new `ifdef` tag.

I'd guess that 1 is easier to implement, and it's probably what the user wants in this situation. The only reason that comes to mind to prefer 2 or 3 is to be able to catch typos à la
```
{% if somevra %} This is {{ somevar }} {% else %} Default text. {% endif %}
```
(note the typo in the first instance of `somevar`).

**Comment by sschuldenzucker** [comment]
So I've checked out the code and I volunteer to implement this.

But I'd like some feedback on the preferred approach first.

My favorites, in order, are:

* 1 — Most preferred. Easy to implement & prob what the user expects.
* 3 — Also fine.
* 2 — Feels a bit messy to me. AFAIU there are currently no textual *functions* in expressions (only operators), so something like `{% if defined(somevar) %}` isn't really lexically defined. We might use a unary operator `{% if ?somevar %}`, but it feels unnecessarily complicated.

On a related matter, I feel that it also makes sense to adjust the behavior of the `default` filter so that `{{somevar | default: "nothing"}}` evaluates to "nothing" if `somevar` is undefined. This could by done by patching `Value.value()`.

— A bit messy, I know, but I believe it fits user expectations very closely.

What do you think?

**Comment by harttle** [comment]
Thank you for your exploration on this! LiquidJS is not meant to invent and maintain a whole new language, we just port Liquid language to JavaScript and adjust some behaviours to JavaScript convention.

So I prefer 1 but it should be done by adding an [option](https://github.com/harttle/liquidjs/blob/9d9c0c1ca747ea3b92b2ca59457de5818bf321c5/src/liquid-options.ts#L7) so that the default behaviour is not changed. Because I believe it also makes sense in some (if any, like you mentioned above) cases and when shopify/liquid decided to move on, we can simply enable that option by default.

**Comment by sschuldenzucker** [comment]
Makes sense! So I'll go and see how to implement 1.

------ Original Message ------
