### ISSUE TITLE
Trying to access an object value using result of another expression returns entire object

### ISSUE THREAD

**Issue by clottman** [harttle/liquidjs#376]
Hello! 

This is kinda hard to explain, so I made a [nice little gist](https://gist.github.com/clottman/7eb2f9ed8b917d84bb2c621e1a21e466) showing the liquid code, the expected output, and the actual output. 

Basically, if I have an object called `testdata` available to my liquid template that's defined as `{itemkey1: itemvalue1, itemkey2: itemvalue2}`, and I try to access the first key using bracket notation, I get a different result if I pass in the key vs. if I pass in an expression (like getting the first value of an array, where the array is all the keys of `testdata`). If you pass in an expression to `testdata[ ]`, the thing returned will be the entire object, not the value you want from the object.

Here is the example [on Glitch](https://glitch.com/edit/#!/liquid-object-acc-demo?path=src%2Findex.liquid%3A43%3A6); in my example, liquid is being used in Eleventy.

**Comment by pdehaan** [comment]
@clottman I'm a bit confused.

```js
  "devDependencies": {
    "@11ty/eleventy": "^0.11.1"
  },
```

That feels like an older version of Eleventy (2020-10-22, per <kbd>npm info @11ty/eleventy time | grep 0.11.1</kbd>). Latest stable release is v0.12.1 (although that includes liquidjs@6.4.3, if I recall correctly). I see you have a newer version of liquidjs in the package.json, but not sure which version Eleventy is using since I don't see you overriding the liquidjs engine in .eleventy.js config file.

```sh
LINE A itemvalue1
LINE B  {"itemkey1":"itemvalue1","itemkey2":"itemvalue2","itemkey3":"itemvalue3"}

# liquidjs 6.4.3
# Wrote 1 files in 0.10 seconds (v0.12.1)
```

If I run <kbd>npm i @11ty/eleventy@canary</kbd> to update to the bleeding edge Eleventy w/ liquidjs@9, that seems to include liquidjs 9.25.1 and gives me the following output.

```sh
LINE A itemvalue1
LINE B  itemvalue1

# liquidjs 9.25.1
# Wrote 1 files in 0.10 seconds (v1.0.0-canary.39)
```

So it appears this is working as expected in the canary v1 builds of Eleventy, w/ liquidjs@9, but not in liquidjs@6. You might need to see if you can shim the latest version of liquidjs into Eleventy v0.12.1, or possibly wait for Eleventy v1.

**Comment by clottman** [comment]
Oh you're right! I didn't realize liquid was included in Eleventy, so the version in package.json actually wasn't being used after all. 

I upgraded the project to Eleventy 0.12.1 and am still seeing the same behavior. 

Either way, I'm glad to hear this is something that is fixed in newer versions of liquid; seems like it's something Eleventy needs to update in pre-canary builds if it needs to work there.

Thanks so much for your response.

**Comment by pdehaan** [comment]
I think you can shim liquidjs@9 into Eleventy v0.12.x using something like the following (although you might need to hack around with the options to make sure liquidjs knows where to find the `_includes/` folder, etc):

```js
// .eleventy.js

const { Liquid } = require("liquidjs"); // `npm i liquidjs@latest`

module.exports = (eleventyConfig) => {
  eleventyConfig.setLibrary("liquid", new Liquid({}));

  eleventyConfig.addFilter("inspect", require("util").inspect);
  return {};
}
```

I don't think this will be addressed in pre-canary Eleventy v1 since it'd be a potentially breaking change and would be tricky to force into an Eleventy 0.13.x version bump.
