### ISSUE TITLE
leaking JS prototype getter functions in evaluation (eg, .length)

### ISSUE THREAD

**Issue by amit777** [harttle/liquidjs#454]
I noticed that javascript string and array prototype functions may be getting leaked.  I actually like some of them like `str.length` or `arr_var.length`  rather than using `str | size`  or `arr_var | size`.   This seems to be non-standard liquid templating.  

I'm just asking because I would like to keep the `.length` since it is more ergonomic when used in `{% if str.length > 5 %} ... {% endif %}` 

I'm worried it may be removed in a future "fix".  Is this a bug or a feature that getters like .length or .toUpperCase work?

**Comment by amit777** [comment]
And if you do plan on removing access to the getter functions, I wonder if there could be  flag to keep the existing functionality.

**Comment by harttle** [comment]
Related to #254 but this is more specific. I'll treat this as a feature request and leave this open for further discussion.

I don't have a good idea to restrict prototype access since we had discussion on #254, because we cannot tell whether a property is from prototype or not. Currently we rely on users only pass sanitized plain object into LiquidJS as scope and modifying builtin prototype is considered bad practice.

Consider this case:

```javascript
let proto = { foo: 'FOO' }
let obj1 = Object.create(proto)
let obj2 = Object.create(proto)
obj2.foo = 'FOO'

isFromProto(obj1, 'foo') // expect true
isFromProto(obj2, 'foo') // expect false

// we cannot implement such a `isFromProto` for both of following are true
obj1.__proto__.foo === obj1.foo
obj2.__proto__.foo === obj2.foo
```

A white list like `allowedJsGetters` will affect all objects and that property would be nolonger valid as variable/property name. Need more discussion. Maybe removing `__proto__` recursively on `scope` is also a solution?

**Comment by amit777** [comment]
I’ll ask one of JS experts his thoughts on this. My initial thought would
be to use the hasOwnProperty() method to check if the key belongs to the
object or is it inherited. I’m not sure if you have considered this?  Would
you be able to point me to the code that executes the inherited method?

**Comment by harttle** [comment]
> use the hasOwnProperty() method to check if the key belongs to the
object

Good idea. It works fine with the above the above case I posted, and also works for `Array.prototype.length`.

```javascript
Object.hasOwnProperty(Object.create({foo: 'foo'}), 'foo') // false
Object.hasOwnProperty([1,2], 'length') // false
class Foo { foo() {} }
Object.hasOwnProperty(new Foo(), 'foo') // false, does this make sense?
```

> Would
you be able to point me to the code that executes the inherited method?

https://github.com/harttle/liquidjs/blob/8db6c7b28ddbcc9c9ddc09801a11f994923a7a07/src/context/context.ts#L90

**Comment by jg-rp** [comment]
I don't think [commit 7e99efc](https://github.com/harttle/liquidjs/commit/7e99efc5131e20cf3f59e1fc2c371a15aa4109db) is solving this issue as intended. 

```javascript
const { Liquid } = require("liquidjs");
const engine = new Liquid({ ownPropertyOnly: true });
engine.parseAndRender("{{ a.length }}", { a: ["a", "b", "c"] }).then(console.log);
``` 

**Output:**
```plain
3
```
Notice from your examples that `Object.hasOwnProperty([1,2], 'length')` (without `.call`) is equal to `false`, but `Object.hasOwnProperty.call([1,2], 'length')` is equal to `true`.

Perhaps a solution using [Object.propertyIsEnumerable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/propertyIsEnumerable) would be more appropriate. 

```javascript
Object.propertyIsEnumerable.call(Object.create({foo: 'foo'}), 'foo') // false
Object.propertyIsEnumerable.call([1,2], 'length') // false
Object.propertyIsEnumerable.call("", 'length') // false
```

**Comment by harttle** [comment]
> I don't think [commit 7e99efc](https://github.com/harttle/liquidjs/commit/7e99efc5131e20cf3f59e1fc2c371a15aa4109db) is solving this issue as intended.

Yes, that is not solving the "eg, .length" isssue, but it does solve "reading from prototype" issue. By definition, use `hasOwnProperty` can prevent from reading from prototype chain (chained `__proto__` property in most implementations).

Actually `.length` is not on the prototype, as you can see in:

```javascript
// own property
> [1,2].length
2
// prototype also has this property, but not the intended one
> [1,2].__proto__.length
```


Here's a better explanation on [stackoverflow](https://stackoverflow.com/questions/50999669/why-arrays-have-a-given-property-length-why-its-not-in-prototype) about why it's not on prototype. And I don't think reading array length in template is a potential security issue, it's an `Array` after all, otherwise why not use object.

BTW, `Object.hasOwnProperty([1,2], 'length')` is a misuse, the `[1,2]` will be interperated as `property name` and `length` will be ignored. This call will always return false for any object. Further explained:

```
> a = {foo: 'bar'}
{ foo: 'bar' }
// aparently
> a.hasOwnProperty('foo')
true
// Object don't have a a property
> Object.hasOwnProperty(a, 'foo')
false
// Object.create is its own property
> Object.hasOwnProperty('create')
true
```
