### ISSUE TITLE
Export `LiquidExpression` class or `evalExpression` to evaluate single expressions

### ISSUE THREAD

**Issue by Prinzhorn** [harttle/liquidjs#527]
First of all thanks for creating and maintaining LiquidJS. I needed a white space sensitive generic templating language that is not tied to HTML and LiquidJS does exactly that.

Now I have a requirement that I think this library could very easily fulfill as well. You are probably aware how GitHub actions allows using templating and conditions inside YAML. E.g.

```yml
if: github.repository == 'octo-org/octo-repo-prod'
```

or 

```yml
if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
```

I have a very similar requirement (not sure yet if it will use YAML as well). Since I am already using LiquidJS I would love to use the same semantics here as well. But Instead of rendering a template and getting a string as a result I would need LiquidJS to evaluate a single expression and return the value as is (boolean, number, etc.). It would look like this:

```js
import { LiquidExpression } from 'liquidjs';

const expressionEngine = new LiquidExpression();
const expression = expressionEngine.parse('a > b');
const result = expressionEngine.evaluate(expression, {a: 1, b: 2});

// In this specific case the expression yielded a boolean, but it could be any primitive.
assert(result === false);
```

---

I've been poking around the docs and code and I _think_ what I want is a more ergonomic way of doing this?

https://github.com/harttle/liquidjs/blob/753e8f94c0560a16ee41cb610627f39431bc361d/test/unit/render/expression.ts#L10-L12

Maybe add `evalExpression` analogous to `evalValue`?

**Comment by harttle** [comment]
Thank you for digging into the codebase and provide the snippet!

There was a [keepOutputType](https://liquidjs.com/api/interfaces/liquid_options_.liquidoptions.html#Optional-keepOutputType) option to allow `.render()` to return a primitive value when the input contains only one expression like `{{ a < b }}`. But it's still Liquid syntax not a pure Expression you described above.

Actually `Expression` is already exported, but you need more to do it properly. I exported some other utilities, and added one test case you may find useful:

https://github.com/harttle/liquidjs/blob/e874b4060b46195e05a5cc6690626bdaa532154c/test/e2e/issues.ts#L263-L268

**Comment by harttle** [comment]
Makes sense! But `evalValue` and `evalExpression` can be confusing, we need to change the API name or maybe we can implement `evalExpression` functionality in `evalValue`. At least expression sounds like a special type of value.

**Comment by Prinzhorn** [comment]
It looks like you've been unhappy with the name for at least four years (https://github.com/harttle/liquidjs/issues/58), but it's up to you if you want to deprecate `evalValue`.

> maybe we can implement `evalExpression` functionality in `evalValue`

That does sound even more confusing if we add a flag or something to `evalValue`.

Maybe `evalOutput` and `evalExpression` would fly. "Outputs" is also the first thing in the tutorial, so the terminology is settled I guess. And "Expression" is generic enough that you would expect any type (bool, string, number, ...) from it.

**Comment by harttle** [comment]
I agree with you that adding a flag to `evalValue` is not appropriate. What I am thinking is `evalValue` can support an expression apart from a variable.

`evalOutput` is useless if input is like `{{val}}`, because `parseAndRender` does exactly the same thing.

Currently `evalValue` accepts input like `obj.prop` and optionally with filters like `obj.prop | capitalize`, and already returns any type (bool, string, number, ...) without converting to string.

The concept of `Output`(`{{foo}}`) is on the same level of `Tag`(`{%foo%}`). And `Value`(`foo`) is just on the right level to represent expressions.

**Comment by Prinzhorn** [comment]
I see, sounds good. I clearly don't know enough about the internals :smile:

**Comment by harttle** [comment]
I find `evalValue` actually support expressions like `a > b`, but the second parameter is `Context` instead of plain object.

`evalValue` is no longer used by liquidjs itself so I guess there's no reason to continue using a internal `Context` class as argument. On v9.41.0 plain object is supported. Please refer to this test case:

https://github.com/harttle/liquidjs/blob/071368afe1c4fd36ebdb0e1d300c367db1766f7f/test/e2e/issues.ts#L269-L278

**Comment by Prinzhorn** [comment]
That's amazing! Was playing with it to see if it fully solves my use-case and opened #533 for that
