### ISSUE TITLE
date filter should return parsed input when no format is provided

### ISSUE THREAD

**Issue by sebastienros** [harttle/liquidjs#573]
Expected:

![image](https://user-images.githubusercontent.com/1165805/208783625-845301d6-4507-4c36-b7ea-95621c14924f.png)

Actual:
https://liquidjs.com/playground.html#e3sgJ25vdycgfCBkYXRlIH19Cnt7ICcyMDIyLTEyLTA3VDIyOjIyOjE4JyB8IGRhdGUgfX0K,e30=

**Comment by harttle** [comment]
> Date.toString()

I find this approach is not feasible for `TimezoneDate`. Now I'm trying to set the default format string to `'%A, %B %-e, %Y at %-l:%M %P %z'` when it's not provided, so that the use case you provided can pass the test.

It seems OK in this test case: https://github.com/harttle/liquidjs/blob/3f21382d43cafa1e32162e58adabd22d5c3709ed/test/integration/filters/date.ts#L70-L72

The timezone is specified so that this test case can be env independant, more realistic use case is:

https://github.com/harttle/liquidjs/blob/3f21382d43cafa1e32162e58adabd22d5c3709ed/test/integration/filters/date.ts#L9-L11
