### ISSUE TITLE
paginate tag does not supported

### ISSUE THREAD

**Issue by sonnht1409** [harttle/liquidjs#66]
Seem you haven't support {% paginate %} tag yet. Is there any solution to render them?
Currently my code look like this, did I used it on wrong way?
{% paginate list by limit %}
 {% for %}
{% endfor %}
{% endpaginate %}

**Comment by harttle** [comment]
Do you mean this API: https://help.shopify.com/themes/liquid/objects/paginate? It's not implemented yet, a PR is welcome.

**Comment by harttle** [comment]
liquidjs is expected to be implementing the [Liquid](https://shopify.github.io/liquid/) templating language. Domain specific objects like `paginate`, `shop`, `order` will not be implemented within this project. Closing

**Comment by stephengardner** [comment]
I'm trying to implement something like this and would really like to know the general concept behind how that would be achieved.

Its my belief that in the registration of tags, we can grab data from some outside data source and then parse things accordingly? 

I'm incredibly confused by that, specially if the pagination contents contain another section or something similarly confusing.

I'll be over here reading all these closed issues to see if anything helps :)

**Comment by harttle** [comment]
Just push a context object with a `paginate` property into the scope, the `paginate` variable will be available during the following render until that context is popped out, see: https://github.com/harttle/liquidjs/blob/08646f75b05f14c172e3242714d06e8425417240/src/builtin/tags/for.ts#L65-L79

It seems that `paginate` tag is not business related, thus it's great to integrate it into this repo. PR is welcome if you're willing to.

**Comment by stephengardner** [comment]
@harttle I greatly appreciate the suggestion.  I've been working with the repo for a while, but I'm stuck with understanding its entirely.  For example, how the "context" actually works, and its purpose.  Since it doesn't appear to be documented anywhere.  Further, for the built-in functions (like "include"), there are a number of included typescript files which don't actually bundle with the `npm install`ed version of the repo.  I'm just wondering if there's any additional place to get up-to-speed with some advanced tag functions (like a `section` or `paginate` tag, both of which have been raised before, and both of which happen to be necessary for us)

**Comment by harttle** [comment]
Unfortunately there's no such document currently, I'd rather remain the source code self-explained for now until there's more people asking questions. Nevertheless, feel free to submit an issue if something confuse you, the implementation details need to be discussed and to be shipped to better design.

For the `Context` object, it's a stack structure intended to maintain nested scopes, like:

```javascript
{% for i in (1..5) %}
  {{forloop.index}}
  {% for i in (1..5) %}
    {{forloop.index}}
  {% endfor %}
{% endfor %}
```

There's two distinct `forloop` variables existing at the same time, and they're pushed into the scope stack when rendering each `{%for%}` tag and popped after the corresponding `{%endfor%}` tag. So if you need to potentially shade some variables rather than overwrite, just push a scope and remember to pop after done rendering.

**Comment by Ben-Abbes** [comment]
@harttle Is there any news about the pagination "tag" ?
This would be useful if it was implemented, since it is a liquid logical tag and not specific to the shopify ecosystem only.
Thank you in advance

**Comment by Ben-Abbes** [comment]
@stephengardner Have you found a solution?

**Comment by harttle** [comment]
You'll need both a `{%paginate%}` tag and a corresponding [paginate object](https://shopify.dev/docs/liquid/reference/objects/paginate) to make it work. That's not part of the responsibility of a template engine.

I suggest to implement it in the context of your app which has the information of url params and responsible to define the `paginate` object. LiquidJS now supports global variables via the [globals](https://harttle.land/liquidjs/interfaces/_liquid_options_.liquidoptions.html#globals) options, more discuss see https://github.com/harttle/liquidjs/issues/185
